---
- name: K8s cluster deployment
  hosts: all

  pre_tasks:
    - name: Ensure Kubernetes API is allowed through firewall
      become: true
      community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp

  roles:
    - dannixon.k8s.k3s_install

  tasks:
    - name: Save kubeconfig to localhost
      run_once: true
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ kubeconfig.content | b64decode | regex_replace('127\\.0\\.0\\.1', ansible_host) }}"
        dest: "{{ lookup('env', 'KUBECONFIG') }}"
        mode: "u=rw,g=,o="
