---
collections:
  - git+https://github.com/DanNixon/ansible-k8s.git
  - git+https://github.com/DanNixon/ansible-services.git
  - git+https://github.com/DanNixon/ansible-system.git
  - git+https://github.com/DanNixon/dotfiles.git#/dotfiles
