---
- name: System configuration
  hosts: all

  roles:
    - dannixon.system.package_updates
    - dannixon.system.system
    - dannixon.system.disable_swap
    - dannixon.system.inspection_tools
    - dannixon.system.interactive_users
    - dannixon.services.sshd

    - archive_backup_mount

  tasks:
    - name: Ensure firewall is enabled
      become: true
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Ensure SSH is allowed through firewall
      become: true
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Ensure OpenZFS userspace tools are installed
      become: true
      ansible.builtin.package:
        name: zfsutils-linux
        state: present

    - name: Ensure misc packages are installed
      become: true
      ansible.builtin.package:
        name:
          - cmake
          - make
          - g++
          - libhdf5-dev
        state: present
