---
- name: Ensure dependencies are installed
  become: true
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Create mountpoint
  become: true
  ansible.builtin.file:
    path: /supermusr_archive
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure credentials file is present
  become: true
  ansible.builtin.template:
    src: supermusr_archive.creds
    dest: /
    owner: root
    group: root
    mode: "u=rwx,g=,o="

- name: Ensure mount is configured
  become: true
  ansible.builtin.mount:
    path: /supermusr_archive
    src: "//isisarvr80new.isis.cclrc.ac.uk/supermusrtestdatabackup$"
    fstype: cifs
    opts: "uid=supermusr,noserverino,vers=2.1,credentials=/supermusr_archive.creds,_netdev"
    state: mounted
